"""add_openrouter_max_tokens_to_user_profile

Revision ID: f2ec23048f2f
Revises: fd4b57aaa070
Create Date: 2026-08-24 09:52:06.620061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ec23048f2f'
down_revision: Union[str, Sequence[str], None] = 'fd4b57aaa070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openrouter_max_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('openrouter_max_tokens')

    # ### end Alembic commands ###
