"""add_app_settings

Revision ID: fd4b57aaa070
Revises: aeec14c32f66
Create Date: 2026-08-20 20:36:59.861434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4b57aaa070'
down_revision: Union[str, Sequence[str], None] = 'aeec14c32f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_hour', sa.Integer(), nullable=False),
    sa.Column('pipeline_minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
